#ifndef CONSTANTES_H_INCLUDED
#define CONSTANTES_H_INCLUDED

#define MAX_PSEUDO 30
#define MAX_DATE 20
#define MAX_SCORES 100
#define MAX_JOUEURS 10
#define MAX_DISTRIBUTEURS 3
#define MAX_BONBONS 100
#define MAX_COMBINAISONS 50
#endif // CONSTANTES_H_INCLUDED


